#!/bin/bash

# This script compile the software and loads the bin files into the web flash tool
# in the Gitpod Docker container.
# The web flashtool can be started from the Github website with: 
# http://YourGitHubName.github.io/LoRa-Boat-Monitor/flash_tool/esp_flash_tool.html

# Attention! Start this cript only in the Gitpod Docker container.
# Start the script with: bash run

# Path definitions
projectpath="./.pio/build/d1_mini"
toolpath="./docs/flash_tool"

# Install tools
echo "Installing tools"
pip3 install -U esptool
pip3 install -platformio

# Compile the firmware
echo "Compiling Firmware"
platformio run

# Copy all bin files in docs folder for online flash tool
echo "Copy bin files"
cp $projectpath/firmware.bin $toolpath/firmware.bin
echo "Successfully executed"